# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyevent',
            name='category',
        ),
        migrations.AddField(
            model_name='buyevent',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
