# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171001_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='typecustomer',
            new_name='is_typecustomer',
        ),
    ]
