# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171015_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyevent',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
    ]
