# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ChangeCustomerProfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.CharField(choices=[('C', 'Cliente'), ('E', 'Empresa')], default='C', max_length=1),
        ),
    ]
