# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171015_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyevent',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
