# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171018_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyevent',
            name='category',
        ),
        migrations.AddField(
            model_name='buyevent',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
