# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171020_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
