# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171020_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
