# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customer_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
