# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_customer_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyevent',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
