# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171022_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cnpj_cpf',
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ie',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_type',
            field=models.CharField(choices=[('f', 'fisica'), ('j', 'juridica')], default='F', max_length=1, verbose_name='Fisica ou Juridica'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='buyevent',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.CharField(blank=True, choices=[('v', 'vendedor'), ('c', 'comprador')], max_length=1, verbose_name='tipo de cliente'),
        ),
    ]
