# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171025_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler',
            name='razaosocial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='state_province',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
