# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0019_auto_20171025_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('endereco', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('pais', models.CharField(max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
            ],
            options={
                'verbose_name': 'comprador',
                'verbose_name_plural': 'compradores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EventoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeproduto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=19)),
                ('facebook_likes', models.IntegerField(default=0)),
                ('imagemproduto', models.ImageField(blank=True, upload_to='')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comprador')),
            ],
            options={
                'verbose_name': 'eventocompra',
                'verbose_name_plural': 'eventoscompras',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('razaosocial', models.CharField(max_length=50, null=True)),
                ('endereco', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('pais', models.CharField(max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=12, null=True, verbose_name='inscrição estadual')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='buyevent',
            name='buyerid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='saler',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='BuyEvent',
        ),
        migrations.DeleteModel(
            name='Saler',
        ),
    ]
