# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171027_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocompra',
            name='categoriaproduto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaProduto'),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventocompra',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
