# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171027_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
